apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-svc-datanath-metamodelo-dev
  namespace: app-svc-datanath-metamodelo-dev
  labels:
    app: group-app-svc-datanath-metamodelo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-app-svc-datanath-metamodelo-dev
      tier: deployment-svc-datanath-metamodelo-dev
      track: stable
  template:
    metadata:
      labels:
        app: group-app-svc-datanath-metamodelo-dev
        tier: deployment-svc-datanath-metamodelo-dev
        track: stable
    spec:
      containers:
        - name: svc-datanath-metamodelo-dev
          image: "kfcregistry.azurecr.io/svc-datanath-metamodelo-dev:v1.0.0"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
              ephemeral-storage: 100Mi
            requests:
              cpu: "200m"
              memory: "512Mi"
              ephemeral-storage: 50Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 5223